GOVUKAPP-591 Forced Update
alphagov/govuk-mobile-ios-app pull request #104
Opened 2024-10-04 13:57 UTC by TimGJD

Add app forced update screen and logic to show it

[Link to Jira](https://govukverify.atlassian.net/browse/GOVUKAPP-591)

[Link to Figma](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=363-6730&node-type=section&t=ISmPGTBwHk6ZtgdH-0)

![test_loadInNavigationController_dark_rendersCorrectly@3x](https://github.com/user-attachments/assets/8c927a0b-360c-426f-8a8e-6d0efb7c74a1)

![test_loadInNavigationController_light_rendersCorrectly@3x](https://github.com/user-attachments/assets/d22915da-c29d-46c4-af63-6119ab3d82ef)

2024-10-07 09:13 UTC, batesyuk approved these changes

2024-10-07 09:13 UTC, batesyuk commented on Tests/govuk_ios/govuk_ios_unit_tests/Specs/Extensions/Foundation/String+ExtensionsTests.swift
> +    func isVersion_returnsExpectedResult() {
Infact `TopicTests` might be a good one with the zip implementation for arguments

2024-10-07 09:13 UTC, batesyuk requested changes
Approved before by accident

2024-10-07 14:55 UTC, TimGJD commented on Production/govuk_ios/Extensions/Foundation/Bundle+AppVersionProvider.swift
Done

2024-10-07 14:55 UTC, TimGJD commented on Production/govuk_ios/ViewModels/AppForcedUpdateContainerViewModel.swift
> +    let appStoreAppUrl = Constants.API.appStoreAppUrl
Done

2024-10-07 14:55 UTC, TimGJD commented on Tests/govuk_ios/govuk_ios_unit_tests/Specs/Extensions/Foundation/String+ExtensionsTests.swift
> +    func isVersion_returnsExpectedResult() {
Done

2024-10-07 14:55 UTC, TimGJD commented on Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/AppForcedUpdateCoordinatorTests.swift
> +    func start_isAppForcedUpdate_falseCallsDismiss() async {
Done

2024-10-08 08:52 UTC, batesyuk approved these changes

2024-10-08 08:54 UTC, merged