GOVUKAPP-589 Global ON / OFF Switch Post Amigos Feedback
alphagov/govuk-mobile-ios-app pull request #112
Opened 2024-10-09 14:27 UTC by TimGJD

- Fix font size and spacing
- Create reusable header view
- Update button text to new requirement
- Add new grey divider that has appeared on Analytics Consent screen design since Post Amigos
- Respect the notch
- Remove bottom padding from all views that are anchored to the bottom of the screen to match onboarding as requested

2024-10-10 15:39 UTC, batesyuk requested changes

2024-10-10 15:39 UTC, batesyuk commented on Production/govuk_ios/SwiftUIViews/HeaderView.swift
> +    public init(title: String, subheading: String) {
No need for `public` here

2024-10-10 15:39 UTC, batesyuk commented on Production/govuk_ios/SwiftUIViews/HeaderView.swift
> +    public var body: some View {
No need for `public` here?

2024-10-10 15:50 UTC, TimGJD commented on Production/govuk_ios/SwiftUIViews/HeaderView.swift
> +    public init(title: String, subheading: String) {
Done

2024-10-10 15:50 UTC, TimGJD commented on Production/govuk_ios/SwiftUIViews/HeaderView.swift
> +    public var body: some View {
Done

2024-10-11 07:31 UTC, batesyuk approved these changes

2024-10-11 08:01 UTC, merged