[GOVUKAPP-605 & GOVUKAPP-604] Fix homepage visual bugs
alphagov/govuk-mobile-ios-app pull request #36
Opened 2024-07-30 13:08 UTC by 1pretz1

2024-08-05 08:34 UTC, raphaelolu requested changes

2024-08-05 08:34 UTC, raphaelolu commented on Production/govuk_ios/ViewControllers/BaseViewController.swift
> +//    override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
You have left the comments in

2024-08-05 08:34 UTC, raphaelolu commented on Production/govuk_ios/Views/HomeWidgetView.swift
> +        heightAnchor.constraint(
In other places you have used NSLayoutConstraint.activate, probably best to do that here to keep it consistent

2024-08-05 15:12 UTC, 1pretz1 commented on Production/govuk_ios/ViewControllers/BaseViewController.swift
> +//    override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
Removed 👍

2024-08-05 19:46 UTC, batesyuk approved these changes

2024-08-06 00:02 UTC, raphaelolu approved these changes

2024-08-06 07:47 UTC, merged