GOVUKAPP-672: settings screen
alphagov/govuk-mobile-ios-app pull request #44
Opened 2024-08-20 15:37 UTC by robinphillips

2024-08-27 07:50 UTC, batesyuk requested changes

2024-08-27 07:50 UTC, batesyuk commented on Production/govuk_ios/ViewControllers/SettingsViewController.swift
> +        let screen = AnalyticsScreen(
Is there a reason that the pattern used in `HomeViewController` i.e making the view controller conform to `TrackableScreen` wasn't suitable here?
Also, I think the tracking tag doesn't match the existing pattern as its not all lowercase.
If we stick with this pattern, I would suggest having title and trackingName as separate values in the view model as there is a chance one may change and the other not change. At very least we should have a unit test to validate the tracking title separately so we know if we break it.

2024-08-27 07:50 UTC, batesyuk commented on Production/govuk_ios/ViewControllers/SettingsViewController.swift
> +    private func constraints() {
`configureConstraints` plz

2024-08-27 07:50 UTC, batesyuk commented on Production/govuk_ios/ViewControllers/SettingsViewController.swift
> +    private func addContent() {
`configureUI` plz

2024-08-27 07:50 UTC, batesyuk commented on Tests/GovUK.xctestplan
> +        "argument" : "-UIPreferredContentSizeCategoryName UICTContentSizeCategoryL"
Nice, I think we were having some issues with this before I was on AL

2024-08-27 12:34 UTC, raphaelolu requested changes

2024-08-27 12:34 UTC, raphaelolu commented on Production/govuk_ios/ViewControllers/SettingsViewController.swift
> +
really minor but theres just a couple of random line breaks in the view did load

2024-08-28 10:49 UTC, batesyuk requested changes

2024-08-28 10:49 UTC, batesyuk commented on Production/govuk_ios/ViewControllers/SettingsViewController.swift
> +        analyticsService.track(screen: self)
As this is a BaseViewController, it is tracked automagically when it conforms to `TrackableScreen` so shouldn't need this.

2024-08-28 10:49 UTC, batesyuk commented on Production/govuk_ios/ViewControllers/SettingsViewController.swift
> +    let scrollview = UIScrollView(frame: .zero)
Should this be `private`?

2024-08-28 15:14 UTC, batesyuk approved these changes

2024-08-29 08:46 UTC, raphaelolu approved these changes

2024-08-29 08:49 UTC, merged